name: Publish mosip-helm charts

on:
  workflow_call:
    inputs:
      HELM_REPO_URL:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  publish-helm-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Setup Branch and Env
        run: |
          # Strip git ref prefix from version
          echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV
          echo "COMMIT_ID=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "HELM REPO ACOCUNT : ${{ inputs.HELM_REPO_ACCOUNT }}" 

      - id: files
        uses: syedsalman3753/get-changed-files-in-pr@v1
      - name: save helm/charts to tmp.txt file
        run: |
          touch ./tmp.txt
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "File: ${changed_file}."
            if [[ $changed_file =~ ^[charts] ]]; then 
              echo "${changed_file}" | awk -F '/' '/^[charts]/{print $2}' >> ./tmp.txt; 
              echo "Saved $( echo ${changed_file} | awk -F '/' '/^[charts]/{print $2}') chart to tmp.txt"
            fi
          done
          cat tmp.txt | sort | uniq > ./tmp1.txt
          mv ./tmp1.txt ./tmp.txt
          echo "List of charts to be published";
          cat ./tmp.txt

      - name: Generate tar files
        run: |
          echo "BRANCH_NAME=$BRANCH_NAME";
          helm repo add mosip ${{ inputs.HELM_REPO_URL }}

          echo "COMMIT=${{ env.COMMIT_ID }}"
          echo "SKIP=FALSE" >> $GITHUB_ENV
          if [[ ! -s ./tmp.txt ]]; then 
            echo "No Charts to publish"; 
            echo "SKIP=TRUE" >> $GITHUB_ENV
          fi
          #cd charts &&
          #find * -prune -type d > ../tmp.txt
          #cd ..

          while IFS= read -r line; do
            fullpath=$line
            echo "Pullpath: $fullpath"
            fullname=$(basename "$line")
            echo "Filename: $fullname"
            if [[ ! -d charts/$fullpath/ ]]; then 
              echo "chart directory $fullpath in list 'tmp.txt' not found; SKIPPING"; 
              continue; 
            fi
            helm dependency update charts/$fullpath/
            helm package charts/$fullpath
          done < tmp.txt
          if ! ls *.tgz 1> /dev/null 2>&1; then
            echo "no tar files generated"
            echo "SKIP=TRUE" >> $GITHUB_ENV
          fi

      - name: Upload tar as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: charts
          path: ./*.tgz
          retention-days: 1
        if: env.SKIP != 'TRUE'

      - name: Checkout branch for publishing
        uses: actions/checkout@v3
        with:
          ref: gh-pages
        if: env.SKIP != 'TRUE'

      - name: Download tar from Artifacts
        uses: actions/download-artifact@v3
        with:
          name: charts
          path: ./
        if: env.SKIP != 'TRUE'

      - name: Update index.yaml
        run: |
          git status
          helm repo index --url ${{ inputs.HELM_REPO_URL }} .
        if: env.SKIP != 'TRUE'

      - name: Commit Changes to mosip-helm Repository
        uses: EndBug/add-and-commit@v7
        with:
          branch: gh-pages
          default_author: github_actions
          message: 'added helm charts for release ${{ github.event.inputs.git-ref }}'
          add: './*.tgz ./index.yaml'
        if: env.SKIP != 'TRUE'

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,author,commit,workflow,job # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: failure() # Pick up events even if the job fails or is canceled.