name: Run Lint and Test Charts manually

on:
  workflow_call:
    inputs:
      TARGET_REPO:
        description: 'target repo'
        required: true
        default: 'https://github.com/mosip/mosip-helm'
        type: string
      TARGET_BRANCH:
        description: 'target branch'
        required: true
        default: 'gh-pages'
        type: string
      IGNORE_CHARTS:
        description: 'Ignore linting for list of charts separated by pipe(|)'
        required: true
        default: 'reporting|reporting-init|activemq-artemis'
        type: string
      LINT_ALL_CHARTS:
        description: 'Run chart linting for all charts (yes|no)'
        required: true
        default: 'no'
        type: string

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          # ct needs history to compare
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Install python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true

      - name: Install yamllint via pip3
        run: |
          pip3 install yamllint

      - name: Set environment variables
        run: |
          # echo "TARGET BRANCH : ${{ github.event.inputs.TARGET_BRANCH }}"
          echo "TARGET_BRANCH=$(echo ${{ github.event.inputs.TARGET_BRANCH }} )" >> $GITHUB_ENV
          echo "COMMIT_ID=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "TARGET_REPO=$( echo ${{ github.event.inputs.TARGET_REPO }} )" >> $GITHUB_ENV

      - name: Add Target repo to git remotes
        run: |
          git remote add TARGET_REPO $TARGET_REPO
          git fetch TARGET_REPO

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (lint)
        run: |
          if [ ${{ github.event.inputs.LINT_ALL_CHARTS }} = "yes" ]; then
            ct lint --config=.github/chart-testing-config.yaml --chart-dirs=charts --remote=TARGET_REPO --target-branch=$TARGET_BRANCH;
          else          
            find charts -maxdepth 1 -type d |grep -Ev "^charts$|${{ github.event.inputs.IGNORE_CHARTS }}" > list.txt;
            while read -r chart; do
              echo -e "\nCHART: $chart\n";
              ct lint --config=.github/chart-testing-config.yaml --charts=$chart --remote=TARGET_REPO --target-branch=$TARGET_BRANCH;
            done < ./list.txt
          fi

      - name: Create yaml files for helm charts
        run: |
          while read -r chart; do
            echo -e "\nCHART: $chart\n";
          
            yaml_file='./chart-template.yaml'
            chart_name=$( echo $chart | awk -F / '{print $2}' );
            mkdir "$chart_name-yaml";
          
            helm template $chart > $yaml_file
            last_line=$( cat -n $yaml_file| tail -n 1 | awk '{print $1}' )
            line_nos="$( awk '/^---/{print NR}' $yaml_file ) $last_line"
            start_of_file=0
          
            for line in $line_nos; do
              if [[ $line -eq 1 ]]; then
                start_of_file=$line;
                continue;
              fi
          
              head_line=$(( line-1 ));
              tail_line=$(( line-start_of_file ));
          
              if [[ $line -eq $last_line ]]; then
                head_line=$line;
                tail_line=$(( line-start_of_file+1 ));
              fi
          
              start_of_file=$line;
              # echo "HEAD LINE: $head_line, TAIL LINE: $tail_line";
          
              yaml_type=$( head -n +$head_line $yaml_file | tail -n $tail_line | grep -c -E "kind\:\ Deployment|kind\:\ StatefulSet" || true );  # used "true" to return exit code as 0
              # echo "YAML TYPE: $yaml_type";
              if [[ "$yaml_type" -eq 0 ]]; then
                 # echo "if YAML TYPE: $yaml_type";
                 continue;
              fi
          
              filename=$( head -n +$head_line $yaml_file | tail -n $tail_line | awk -F '/' '/# Source/{print $3}' );
              echo "$filename";
              head -n +$head_line $yaml_file | tail -n $tail_line > "$chart_name-yaml/$filename";
            done
          done < ./list.txt

      - name: Run Health Check Test
        run: |
          while read -r chart; do
            echo -e "\n\nCHART: $chart\n";
          
            chart_name=$( echo $chart | awk -F / '{print $2}' );
            list=$( ls $chart_name-yaml || true );
          
            echo -e "YAML LIST :";
            echo -e "$list\n"
          
            for yaml in $list; do
              echo -e "YAML : $yaml";
              yamale -s .github/health-check-schema.yaml "$chart_name-yaml/$yaml" --no-strict
            done
          
          done < ./list.txt

      # Commented below tasks as it cannot test MOSIP helm/charts deployment due to dependencies issues
      #- name: Create kind v1.21.1 cluster
      #  uses: helm/kind-action@v1.4.0
      #  with:
      #    node_image: kindest/node:v1.21.1
      #
      #- name: Run chart-testing (install)
      #  run: |
      #    while read -r chart; do
      #      echo -e "\nCHART: $chart\n";
      #      ct install --config=.github/chart-testing-config.yaml --charts=$chart --remote=TARGET_REPO --target-branch=$TARGET_BRANCH;
      #    done < ./list.txt

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,author,commit,workflow,job # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEVOPS_WEBHOOK }} # required
        if: failure() # Pick up events even if the job fails or is canceled.