name:  Manual workflow to transfer docker images

on:
  workflow_call:
    inputs:
      USERNAME:
        description: 'provide docker hub username'
        required: true
        default: ''
        type: string
      DESTINATION_ORGANIZATION:
        description: 'provide docker hub destination org'
        required: true
        default: ''
        type: string
    secrets:
      TOKEN:
        description: 'provide docker hub token'
        required: true

jobs:
  Image-transfer:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: update config.yml
        run: |
          cd release/vidivi
          echo "PWD: $( pwd )"
          echo "LS : $( ls ) "
          sed -i "s/username:.*/username: ${{ github.event.inputs.USERNAME }}/g" config.yml
          sed -i "s/token:.*/token: ${{ secrets.TOKEN }}/g" config.yml
          sed -i "s/destination_organization.*/destination_organization: ${{ github.event.inputs.DESTINATION_ORGANIZATION }}/g" config.yml
      - name: push images
        run: |
          cd release/vidivi
          sudo pip install python-pip
          sudo pip install docker
          sudo python3 vidivi.py push